version: '3.8'

services:
  php:
    build: docker/php
    user: ${HOST_UID-1000}:${HOST_GID-1000}
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - ~/.composer/cache:/tmp/composer_cache:delegated
    environment:
      COMPOSER_AUTH:
      COMPOSER_CACHE_DIR: /tmp/composer_cache
      COMPOSER_MEMORY_LIMIT: -1
