services:
  php:
    build: docker/php
    user: ${HOST_UID-1000}:${HOST_GID-1000}
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.composer/cache:/tmp/composer_cache
    environment:
      COMPOSER_AUTH:
      COMPOSER_CACHE_DIR: /tmp/composer_cache
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  mysql:
    build: docker/mysql
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=0000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      retries: 5

  mongodb:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - mongodb_data:/data/db:rw
    restart: always
    environment:
      MONGODB_INITDB_DATABASE: app
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  nginx:
    build: docker/nginx
    volumes:
      - ./:/app #required if files other than index.php need to be available
    depends_on:
      - php

volumes:
  mysql:
  mongodb_data:
