version: '3.8'

services:
  php:
    build: docker/php
    user: ${HOST_UID-1000}:${HOST_GID-1000}
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - ~/.composer/cache:/tmp/composer_cache:delegated
    environment:
      BLACKFIRE_CLIENT_ID:
      BLACKFIRE_CLIENT_TOKEN:
      COMPOSER_AUTH:
      COMPOSER_CACHE_DIR: /tmp/composer_cache
      COMPOSER_MEMORY_LIMIT: -1

  nginx:
    build: docker/nginx
    volumes:
      - ./:/app:delegated #required if files other than index.php need to be available
    ports:
      - "8000:80"
    depends_on:
      - php

  blackfire:
    depends_on:
      - php
    image: blackfire/blackfire
    ports: ["8707"]
    environment:
      BLACKFIRE_SERVER_ID:
      BLACKFIRE_SERVER_TOKEN:
