services:
  php:
    build: docker/php
    user: ${HOST_UID-1000}:${HOST_GID-1000}
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.composer/cache:/tmp/composer_cache
    environment:
      COMPOSER_AUTH:
      COMPOSER_CACHE_DIR: /tmp/composer_cache
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: docker/mysql
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=0000
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      retries: 5

  nginx:
    build: docker/nginx
    volumes:
      - ./:/app #required if files other than index.php need to be available
    ports:
      - "8000:80"
    depends_on:
      - php

volumes:
  mysql:
