# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\QLS\CreateShipmentLabelController:
        tags: ['controller.service_arguments']
        arguments:
            $tempPath: '/app/var'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\QLS\Client\QlsClient:
        class: App\QLS\Client\GuzzleQlsClient

    App\QLS\ShipmentLabel\ShipmentLabelMerger:
        arguments:
            $tempPath: '/app/var'

    GuzzleHttp\Client:
        arguments:
            $config:
                base_uri: 'https://api.pakketdienstqls.nl'
                auth:
                    - '%env(string:SLQ_BASIC_AUTH_USERNAME)%'
                    - '%env(string:SLQ_BASIC_AUTH_PASSWORD)%'
