---
name: CI

on: [ push ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: Run CI suite

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 0000

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysql

      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --no-progress  --ansi

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --no-progress --ansi

      - name: Run cs-fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation  --ansi

      - name: Run tests
        run: bin/phpunit
