---
name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run CI suite
    env:
      DATABASE_URL: 'mysql://root:0000@127.0.0.1:3306/app'

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: '0000'

    steps:
      - uses: actions/checkout@v4

      - name: Build the stack
        run: make setup

      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v5

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Downloads
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make dependencies

      - name: Run cs-fixer
        run: make qa

      - name: Run tests
        run: make test
